### ISSUE TITLE
Load other file from npm module

### ISSUE THREAD

**Issue by icebob** [cerebral/webpackbin#10]
How can I import a file from an npm module?

It is not working:
```js
  import VueFormGenerator from "vue-form-generator/dist/vfg-core.js";
  import "vue-form-generator/dist/vfg.css";
```

Error:
```
Module not found: Error: Can't resolve 'vue-form-generator/dist/vfg-core.js' in '/app/fd9afff8-24bb-4a4e-a263-bb580a0542fe'
```

Bin: https://www.webpackbin.com/bins/-Ki03eOV65nKuBc_GLy4

**Comment by christianalfoni** [comment]
@icebob Thanks for reporting this :-)

There is an alghoritm that finds possible entrypoints in the packages. The `dist` folder is blacklisted, because many packages uses this folder name to include a bunch of prebundled versions of the package. Like for example vue itself has many versions of vue inside dist folder.

This seems to be a bit strict though. I could rather change it to allow dist folder to be traversed and let the `*.min, *.common, *.esm` blacklisting take care of it instead. (Specific entry points defined in package.json are never blacklisted btw).

Does this make sense from your standpoint?

**Comment by icebob** [comment]
Thanks, this solution is good for me.

**Comment by christianalfoni** [comment]
Okay, I just need to do a little bit of research so I do not mess up other packages, but my intuition tells me this will work ;-)

**Comment by EnigmaCurry** [comment]
I believe I'm running into this same issue with this https://www.webpackbin.com/bins/-Ki6aBoMWdbYlNrKCh5G (If I'm wrong about this, I would love to know that too.)

In my case I'm just importing the root package which has a main entry point in package.json that points to dist/index.js - so this may be another useful test for a fix.

**Comment by christianalfoni** [comment]
@EnigmaCurry The reason cycle-deepstream fails is that the main entry points to "dist/index.js", but it does not exist. Seems to forget to build before publishing?

**Comment by EnigmaCurry** [comment]
I have a postinstall step in package.json that runs 'npm run dist' Is postinstall not run? It does normally for me when I just do a normal "npm install cycle-deepstream"

**Comment by EnigmaCurry** [comment]
@christianalfoni I modified my release to run dist on prepublish instead, so the package does contain a dist now without needing to run postinstall. I guess this is a different thing than the initial issue, thanks!

**Comment by christianalfoni** [comment]
@EnigmaCurry Great :-)

@icebob Have now deployed new version of the packager which has changed its entry point logic and also handling import of css files directly:

https://www.webpackbin.com/bins/-KiEYmba2lrfIQPbZR2R

Your old bin will not work cause that has already been bundled. You either have to add a third package or wait until vue/vue-form-generator has new release the changes version number, causing a new bundle to be created :)

**Comment by icebob** [comment]
Ohh, great! Thank you!
