### ISSUE TITLE
Old webpackbin down

### ISSUE THREAD

**Issue by arildwtv** [cerebral/webpackbin#35]
I have plans of finally migrating my bins to webpackbin 2, but it seems that the old webpackbin is down (for an example, check out this link: https://www.webpackbin.com/4kXjGAw_M). When you click on "Continue to bin", you are directed to an empty Heroku application.

Are there any plans of fixing this?

<img width="440" alt="screen shot 2017-06-11 at 11 54 12" src="https://user-images.githubusercontent.com/575067/27010109-92f07dfc-4e9d-11e7-8a3e-ddc254857bf8.png">

<img width="297" alt="screen shot 2017-06-11 at 11 54 24" src="https://user-images.githubusercontent.com/575067/27010110-94e54a0c-4e9d-11e7-9ace-57317e01030b.png">

**Comment by christianalfoni** [comment]
Hi @arildwtv , sorry but old webpackbin was running for about 2 months after release of the new one. It was costing me like 70$ each month, in addition to even higher costs now on the new webpackbin... so I took it down after those 2 months, meaning it is gone now :( 

Sorry about that!

**Comment by arildwtv** [comment]
Hi @christianalfoni,

I totally understand the issue with cost. Fortunately, I didn't have that many code examples up on the old one. I guess there could've been harder ways to learn the lesson "always back up your stuff." :)

**Comment by christianalfoni** [comment]
Hehe ;-)

**Comment by TheSharpieOne** [comment]
@christianalfoni is there any way to get the data (not the UI or a way to run the code, just the code that was saved) when trying to view an old Webpackbin? I would be happy to get the raw code so that I can migrate it manually to the new Webpackbin. I 

If the data is still available, it may be possible to migrate it. I would imagine from a data perspective, the old and new are very similar. There are files (code) and configurations (npm, webpack configs, loaders). I know [in this comment](https://github.com/cerebral/webpackbin/issues/12#issuecomment-296113045) you mentioned it was not done due to time constraints. If is it still on option (if the old data still exists), would you be willing to accept help?

Also, you should take down the message and link to the old Webpackbin since they do not work. I can only another ticket to track that if you want.
