### ISSUE TITLE
Load .vue files from node_modules

### ISSUE THREAD

**Issue by ankurk91** [cerebral/webpackbin#37]
Currently it is not possible to load a **.vue** file from node_modules.

I got this error why in try to import a package
```js
import flatPickr from 'vue-flatpickr-component';
```
```
Uncaught Error: Module parse failed: /root/webpack-packager/packages/1093113650/node_modules/vue-flatpickr-component/src/flatPickr.vue Unexpected token (1:0) You may need an appropriate loader to handle this file type. | <template> | | <input type="text"
```
There are various packages which expose .vue file, for example -

https://github.com/ankurk91/vue-flatpickr-component
https://github.com/sagalbot/vue-select

There may be more.

Seems like ``node_modules`` is excluded in vue-loader config.

**Comment by christianalfoni** [comment]
@ankurk91 Hm... the NPM packages are built using a Webpack DLL packager service which does not use any loaders. It is only your BIN that uses a Webpack middleware that attaches loaders.

That said... we could add `.vue` loaders to the DLL packager since those file extensions are so unique. It would only slow down the actual `.vue` files and not general `.js` bundling.

Let me make a quick fix to that. Will get back to you :)
